spring.application.name=guseok-backend

#Database
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#Redis
spring.data.redis.host=${PROD_REDIS_HOST}
spring.data.redis.port=6379

#Kakao OAuth2
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code

#oracle elastic IP
spring.security.oauth2.client.registration.kakao.redirect-uri=http://168.107.63.84:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# ----------------------------------------
# OCI Object Storage (S3 Compatibility API)
# ----------------------------------------
cloud.aws.credentials.access-key=${OCI_ACCESS_KEY}
cloud.aws.credentials.secret-key=${OCI_SECRET_KEY}
cloud.aws.region.static=${OCI_REGION}
cloud.aws.s3.endpoint=https://${OCI_NAMESPACE}.compat.objectstorage.${OCI_REGION}.oraclecloud.com
cloud.aws.s3.bucket=guseok-bucket

#JWT

jwt.secret=${JWT_SECRET}
jwt.access-token-expiry-ms=3600000
jwt.refresh-token-expiry-ms=1209600000

oauth2.redirect-uri=${PROD_FRONTEND_URL}


spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
file.upload.base-dir=uploads